### ISSUE TITLE
Make a Rotting blacklist

### ISSUE THREAD

**Issue by erima** [EnviroMine/EnviroMine-1.7#100]
Would it be possible to make a rotting blacklist? I'm noticing that blue slimes are rotting because they are edible. I can see how it's a powerful system to make all the edible things rot, and I can see a pack maker using this as a thing, but in my use it doesn't make sense that it'd rot.

**Comment by egeis** [comment]
Setting an item to -1 on days to rot already disables rotting on an item.  For example cetting 05.Days To Rot on item_bread in the minecraft config will disable bread from rotting, yum hardtack.

To set it in Tinkers Constructs edit the config file using the editor to alter theTConstructs config > spoilage > item_strangefood, set it to -1 to disable rot.

Found the info under: https://github.com/EnviroMine/EnviroMine-1.7/blob/7f66b36f9a91b88f06e21fe9094f749cd2d9c4e2/src/main/java/enviromine/trackers/properties/RotProperties.java  

This probably need to be in the wiki under rot.

**Comment by erima** [comment]
I agree, I found an example in Enviromine for Rotten Food, but a documented snippet that can be copied from the wiki would be incredibly helpful.

**Comment by GenDeathrow** [comment]
@erima probaly wouldn't be a bad idea to have some documented code snippet.

**Comment by erima** [comment]
I would also recommend adding a note in the enviromine.cfg as well as on the wiki noting that the default time will be overwritten by specific configs in the Custom Properties folder. I didn't realize this folder covered so much, nor could I figure out why carrots were still rotting at 7 days, even though I had changed the default setting.
