### ISSUE TITLE
Server  crashes. "java.lang.NoSuchFieldError: clientQuakes"

### ISSUE THREAD

**Issue by DKPooter** [EnviroMine/EnviroMine-1.7#102]
Server crashes on startup with this error. crash report here: http://pastebin.com/L49dyYHn

**Comment by ignatio** [comment]
This is already identified in the other bug thread about earthquakes.

**Comment by DKPooter** [comment]
No, that thread is about earthquakes making the crash. this is on startup in a fresh world. Also, that error is a java.lang.NoClassDefFoundError: enviromine/world/ClientQuake error. not a NoSuchField error

**Comment by Funwayguy** [comment]
This is the same bug. Earthquakes can spawn on startup in rare occasions.

**Comment by DKPooter** [comment]
Are the earthquakes on startup a world thing? because this happens with every world i try to create.
