### ISSUE TITLE
Server crash on startup

### ISSUE THREAD

**Issue by themaster402** [EnviroMine/EnviroMine-1.7#103]
I am trying to start a server with the other realism mods you mentioned, but it crashes. I picked up a significant few lines of the server console for convenience.

6:12:22 PM [ERROR] [FML] The following problems were captured during this phase
6:12:22 PM [ERROR] [FML] Caught exception from enviromine
6:12:22 PM java.lang.NoSuchFieldError: clientQuakes
6:12:22 PM at enviromine.world.Earthquake.<clinit>(Earthquake.java:34) ~[Earthquake.class:?]

Here is the full crash log.
http://pastebin.com/yqWYDVt0

I am using Enviromine 3.106, which claims to fix an Earthquake bug.

I am using Minecraft 1.7.10

My forge version is 1.7.10-10.13.2.1291

I am using Java 8 Update 31

When I start up the server, it crashes. No complex way.

**Comment by jasonsaffle13** [comment]
does this look like the same as issue #98 I'm not sure.

**Comment by stoops420** [comment]
no this is not the same, I can confirm the same error occurring in the most recent version

**Comment by Funwayguy** [comment]
That's because the fix build hadn't been pushed out to release yet, we were working on other branches. It has been now
