### ISSUE TITLE
[suggestion] Elevator recall block

### ISSUE THREAD

**Issue by demethan** [EnviroMine/EnviroMine-1.7#106]
Hi, 

Love the new cave world. My request is for SMP.  If a player goes down to the cave. no one else can go down because the elevator stays there. 

Would it be possible to have a recall block so two people can go down at the save elevator. 

Thanks.

**Comment by demethan** [comment]
Yes, no, maybe?

**Comment by GenDeathrow** [comment]
It was already added in. @funwayguy had to change it for jttc mod pack.
