### ISSUE TITLE
.DS Store errors on Mac

### ISSUE THREAD

**Issue by Orangyfresh** [EnviroMine/EnviroMine-1.7#110]
Hey, I'm trying to configure a modded block to enable temperature and other variables. When I add the block to MyCustom.cfg by either holding it or looking at it, it creates a .DS Store error in the Custom Configs window. The block is the campfire from the Better Beginnings mod. When I attempt to change the variables, like the temperatures and such nothing happens in game, even after shift+k. 
If this is a simple issue that the two mods are incompatible, then that's fine. But if not then help would be greatly appreciated :)

I believe I am running the most up to date version of Enviromine, in case that helps.
![screen shot 2015-03-06 at 11 57 54 pm](https://cloud.githubusercontent.com/assets/3490913/6525690/ae662938-c45c-11e4-8b02-b9099a33ccc3.png)

**Comment by GenDeathrow** [comment]
Well the ds_store is a Mac issue. I fixed it on loading. But didnt check the ingame menu having he same issue.  As far as the configs not reloading.  Not entirely sure on that yet. Maybe @funwayguy may have an idea.

**Comment by GenDeathrow** [comment]
Sorry my computer died before I was able to fix this issue. I am currently getting my system back up an running.  Hopefully we can get this sorted out. I have bee out for about a month because of it.

**Comment by GenDeathrow** [comment]
This should be fixed in build 114. Sorry for it taking so long. was working on the config update for a while.
