### ISSUE TITLE
[Visual Bug] Wood Plank falling animations (Stairs, fences, etc.)

### ISSUE THREAD

**Issue by Ac1dSn0w** [EnviroMine/EnviroMine-1.7#112]
I notice when placing wooden planks or some items, but in stair or fence types, the falling animations and the landing animation itself change object render. 

Video Link Demonstration: https://vid.me/99BF

[EnviroMine v1.3.107]

**Comment by thislooksfun** [comment]
Yeah, that happens. There is unfortunately no good way of fixing this that I know of. When it lands it fixes itself. Even vanilla (through the spawn entity falling sand thing) messes this up. If anyone finds a good fix for this we'll look into it, but for now it's just not worth it. Sorry.
