### ISSUE TITLE
Earthquakes?

### ISSUE THREAD

**Issue by Deathdemon95** [EnviroMine/EnviroMine-1.7#114]
So, I recently got an earthquake in my world, and I think something went wrong. Because good *god* that was boring as all hell!
I sat there, unable to do anything because my screen was too shaky, my ears were being assaulted with never ending sounds, and what was happening to the world you ask?
*nothing*
Is this right? Do earthquakes really do nothing?
I have them disabled for now because that is just awful IMO

**Comment by thislooksfun** [comment]
They work, they just take a long time (several in-game days by default). I thought we reduced the shaking and sounds, but I could be wrong. You can speed them up in the configs if you want, but that could cause lag.

**Comment by Deathdemon95** [comment]
Wow. Okay no offence, but I'm not sure if you've ever seen an earthquake before.
The destruction pretty much starts as soon as the shaking does. Just saying.

**Comment by thislooksfun** [comment]
No, they start working right away, but it takes a while for the effects to become visible. Yeah, they don't work exactly how they do in the real world, but we are limited in what we can do without lagging the game to crap.
