### ISSUE TITLE
Insanity on Creative

### ISSUE THREAD

**Issue by Darkrose12** [EnviroMine/EnviroMine-1.7#118]
I found that if you switch to creative mode after using /gamemode c while insane, you can't use any commands to get back to survival, you can't sleep, real mobs stop spawning while at nighttime, and even commands such as /kill or /help don't work. So frankly, you end up having to delete that world if you don't have it's file backed up and don't want to be insane. Is there anyway to get back your sanity or kill yourself in creative mode when you're insane?

**Comment by thislooksfun** [comment]
Whooops. Try typing /Envirostat <your name> sanity 100

**Comment by Darkrose12** [comment]
Yeah, unfortunately that's the same thing as the /kill or /help. In chat, it doesn't even show up if the commands have been tried or not so I can't tell what's going on there.

**Comment by thislooksfun** [comment]
Wow, ok. Yeah, we'll look into this. Have you been able to reliably recreate it?

**Comment by Darkrose12** [comment]
I'll see if I can try

**Comment by Darkrose12** [comment]
I replicated it and again, commands or anything didn't work.

**Comment by Darkrose12** [comment]
Unfortunately, the file I recorded was too big to put on but I took a few screenshots. They were all one-after another and I noticed another issue. The zombies and all 'real' mobs for that matter were standing still and I couldn't hit them. They also didn't go away if I switched my game-mode to peaceful.
![2015-03-21_17 17 09](https://cloud.githubusercontent.com/assets/11392277/6764006/0a76741c-cfed-11e4-9944-7939a23388c7.png)
![2015-03-21_17 17 16](https://cloud.githubusercontent.com/assets/11392277/6764007/0ace2748-cfed-11e4-983a-e5163fa91af9.png)
![2015-03-21_17 17 23](https://cloud.githubusercontent.com/assets/11392277/6764008/0b6025a8-cfed-11e4-9511-ee15de55184a.png)
![2015-03-21_17 17 31](https://cloud.githubusercontent.com/assets/11392277/6764009/0c192c9c-cfed-11e4-9101-95dd5bec2f6c.png)

Sorry I couldn't get the video on.

**Comment by Funwayguy** [comment]
Whoa... what version are you using? This is REALLY outdated (at least by a few months)
