### ISSUE TITLE
Chestplates not showing Enchanted "shimmer"

### ISSUE THREAD

**Issue by PitchBright** [EnviroMine/EnviroMine-1.7#122]
Chestplate icons don't shimmer when they are enchanted. They look fine on the player, and in the gui, and in the player's hand, but not when they are in a slot.

I'm able to reproduce this with only Enviromine loaded (no other mods) and a vanilla Iron Chest Plate, as well as when loaded with a bunch of other mods and mod chestplates.

2 Screenshots here: https://imgur.com/Uu1I8gp,ZNGIZa3

**Comment by thislooksfun** [comment]
That's odd. We will look into it when we have time.
(Sorry for not replying earlier, busy week.)

**Comment by Funwayguy** [comment]
I believe this has to do with the custom item renderer for Camel packs not accounting for enchanting shimmer

**Comment by GenDeathrow** [comment]
its a possibility. I need to switch it over to a wrapper so its more mod friendly...

**Comment by PitchBright** [comment]
This is fixed, I believe.
