### ISSUE TITLE
How to make torches not affect temperature?

### ISSUE THREAD

**Issue by moinecraftperv** [EnviroMine/EnviroMine-1.7#124]
I have tried everything, i changed "torches burn, torches go out" = false
i also have tried adding the torch block (vanilla torch, not enviromine) to custom configs, disabling the ambient temperature but it still doesn't work so whenever i spawn in a village i will most likely die from heatstroke if i stay too long
tile_torch {
        S:01.Name=minecraft:torch
        I:02.Damage=-1
        B:"03.Enable Ambient Temperature"=false
        D:"04.Ambient Temperature"=0.0
        D:"05.Ambient Air Quality"=0.0
        D:"06.Ambient Santity"=0.0
        D:"07.Effect Temperature"=0.0
        D:"08.Effect Air Quality"=0.0
        D:"09.Effect Sanity"=0.0
        D:"10.Effect Hydration"=0.0
        D:"11.Effect Temperature Cap"=0.0
        I:"12.CamelPack Fill Amount"=0
        S:"13.CamelPack Return Item"=
        I:"14.CamelPack Return Meta"=0
    }

**Comment by thislooksfun** [comment]
Hmm... That is definitely a bug. That setting should override the torches. We'll look into it. Sorry about that.

**Comment by Funwayguy** [comment]
If there is another entry for the torch in another file (such as minecraft.cfg) the effects may be overridden. Please double check for duplicates

**Comment by GenDeathrow** [comment]
If I am not mistaken before my computer died.  I want to believe I put an error log in if there was a duplicate. So check the error log when you load the game.  It shou 'll d give you an idea where to look.
