### ISSUE TITLE
Torch Overhaul

### ISSUE THREAD

**Issue by jHoyne** [EnviroMine/EnviroMine-1.7#125]
Have you ever thought that the torches in Minecraft where a bit unrealistic well why don't you give them the ability to need to be light them with say a flint and steel or some other item like that and eventually make them run out. Of course with the options to disable those two features.

**Comment by thislooksfun** [comment]
Maybe in the next version. We are just doing bug fixes right now.

**Comment by Funwayguy** [comment]
Pretty sure this is already a thing in EnviroMine

**Comment by jHoyne** [comment]
@Funwayguy haven't noticed is it off default
