### ISSUE TITLE
GUI stats fail to update after user re-logs

### ISSUE THREAD

**Issue by Slothmun** [EnviroMine/EnviroMine-1.7#126]
When I log in to my server the hydration, sanity etc... meters are working fine but when I log out then log in again they are no longer working. They just stay at what they were last at before I logged out. Even effects such as insanity and dehydration stop working when the sanity/water meter clearly state 0.

I thought it may be an issue with the way I had setup the server (on linux with multicraft) and so I tried the server on windows and the same problem occurred.

The only way I have found to fix this is to restart the server but that only fixes the issue until the user re-logs.

**Comment by thislooksfun** [comment]
Hmmm..... That's odd...

**Comment by GenDeathrow** [comment]
Are you still having this issue?

**Comment by Slothmun** [comment]
Yes this bug still exists. It happens when using the BlastOff Modpack, so it could be a conflict with another mod. I've reported it on the BlastOff forums but was directed over here to report it.

If you need a video of what happens, the Yogscast have been having the same problem recently on their last few videos of the series:

https://www.youtube.com/playlist?list=PLGN8WikMb4WH2xrNv9V3SccrlDdm-izkt

**Comment by GenDeathrow** [comment]
Well I look see what could be causing it.  Can't make too many promises I can get it with my fix I want to push late  tonight.

**Comment by Slothmun** [comment]
OK thanks for looking into it :)

**Comment by GenDeathrow** [comment]
Sorry I didn't get back to ya sooner.. It looks like they are using a a version that is about 24 updates behind.. You can tell them to update, or you can at least do it on your modpack. Make sure to back up your stuff before you do though. I am closing this for now.. and will wait for a response.
