### ISSUE TITLE
Ticking memory connection

### ISSUE THREAD

**Issue by Tsyklop** [EnviroMine/EnviroMine-1.7#133]
I open my inventory. I have Camel Pack (Empty) and leather chestplate. I place Camel Pack and chestplate in crafting slot`s. I took the resulting chestplate and game crash.

http://pastebin.com/2rd9fSw4

**Comment by GenDeathrow** [comment]
I cant reproduce this.. any other mods you have that may cause issues?

**Comment by Tsyklop** [comment]
@GenDeathrow No

I think you can close it. Looks like only I had a problem.
