### ISSUE TITLE
Ability to add blocks that ignite gasses

### ISSUE THREAD

**Issue by WolfieWaffle** [EnviroMine/EnviroMine-1.7#142]
Somebody suggested this on the forums, so I put it here. Basically, in the config section, add whether a block can ignite gasses. That way you could add modded torches, hot blocks, etc. to ignite gasses.

**Comment by thislooksfun** [comment]
Interesting idea. We'll consider it for 1.8.

**Comment by GenDeathrow** [comment]
done and done.. I had to push out something than a single fix... this was easy enough

**Comment by WolfieWaffle** [comment]
For 1.8 or 1.7.10?

**Comment by GenDeathrow** [comment]
I know tlf said 1.8. But it was too easy to add in 1.7.10. Its in the newest build.. its located in global config under gasses.
