### ISSUE TITLE
[request] option to hide bars from UI

### ISSUE THREAD

**Issue by Tsunayoshi** [EnviroMine/EnviroMine-1.7#144]
It would be nice to hide some of the disabled bars and in some ways maybe to hide also active bars.

Maybe you can add an option in the ingame config GUI, where you can choose V and H for Vertial and Horizontal, a third option R for remove?

Maybe a bug: (or it is intended)
I am using EnviroMine-1.3.117 and I have disabled water and temp in the configfolder, but the bars are shown anyway.

**Comment by GenDeathrow** [comment]
Its a bug that's showing the bars. When disabled...  its normally happening on servers and lan connections.  I haven't had the time to get to this issue. But guess i will make the time this week. I may add in your request as well. Will be a simple one.

**Comment by GenDeathrow** [comment]
I have a fishing for the bug of the status bars not removing. Will try to get the fix out tonight for me.Hopefully

**Comment by Tsunayoshi** [comment]
Hey that sounds cool. Thank you for your work und time!

**Comment by GenDeathrow** [comment]
the bug should be fixed now....

**Comment by Tsunayoshi** [comment]
I can confirm, the bars are now hidden :)
