### ISSUE TITLE
Insanity still dropping while being attacked by zombies

### ISSUE THREAD

**Issue by WolfieWaffle** [EnviroMine/EnviroMine-1.7#146]
When I put the ambient and attack insanity to zero on zombies, they still drop my sanity a ton. This might be something I'm doing wrong, but I think it shouldn't be doing this. It seems to only affect zombies.

**Comment by GenDeathrow** [comment]
The only like I could see doing it is this -> 
https://github.com/EnviroMine/EnviroMine-1.7/blob/master/src/main/java/enviromine/handlers/EM_EventManager.java#L394-L400

This may be an error.. @Funwayguy may need to make the decision on this,.. Ill ask him about it

**Comment by GenDeathrow** [comment]
Should be fixed on next update 1.3.120, will try get to get it resolved tonight. as long as I dont get any other game breaking issues

**Comment by GenDeathrow** [comment]
this should be resolved.
