### ISSUE TITLE
Insanity slowness: Intentional?

### ISSUE THREAD

**Issue by WolfieWaffle** [EnviroMine/EnviroMine-1.7#147]
Whenever I have insanity effects, I can barely move. Is this intentional? And if so, could you add a config option to disable it?

If it is not intentional, I guess it is a bug :P

**Comment by GenDeathrow** [comment]
are you just using enviromine or using other mods, sounds like it could be an potion ID conflict.

**Comment by WolfieWaffle** [comment]
Hmm, I am using other mods, but when I look at my potion effects, It looks like it's insanity and not any other potions. On an older version, I did have a conflict where instead of "well fed" effect when eating food, you would get dehydration :P. But in this case there does not appear to be any potion effects conflicts. I'll try and isolate the problem.

**Comment by WolfieWaffle** [comment]
I really don't think it's a potion conflict, because IIRC if it was I would be getting a different effect rather than insanity. I am only getting insanity. Secondly, everything works with the insanity how is supposed to besides walking/jumping. Also just as a side note, I think that the hallucinations should actually walk towards you and seem like a real mob. But that's besides the issue at hand :P

**Comment by WolfieWaffle** [comment]
UPDATE: Found the culprit. It's Biomes O Plenty. Try installing the latest version and then getting insanity 3.

**Comment by GenDeathrow** [comment]
We have had other issues with Biomes, also Id like the mobs to move, but Funwayguy told me once it would be feat to do that.
