### ISSUE TITLE
Torches - do place themself on blocks which should open GUI by right-click

### ISSUE THREAD

**Issue by hanakocz** [EnviroMine/EnviroMine-1.7#151]
Hi,
using latest EnviroMine.
I found one annoying thing, that if you click with torch in hand to any block, which has internal GUI, it will place the torch instead of opening the GUI. 
Can you please fix this, so torch places only when there is no GUI to open or the right click does nothing? 

OR...
Can you add the config , that <enviromine:firetorch> drops <minecraft:torch> (default) or <enviromine:firetorch> ? Because if you place your torch, the problem is not there. But now after breaking the torch, only vanilla one is got, which has this bug. (It is easy to change behaviour of recipes to use enviromine torch instead of vanilla one, but the drop you force is breaking the system)
Thanks

**Comment by GenDeathrow** [comment]
Very interesting.. I think I see the issue.. will try and push on the next update

**Comment by GenDeathrow** [comment]
Should be fixed on Version 1.3.120. I am trying to get the update up tonight. Be on the lookout. As long as I don't have any other game breaking issues

**Comment by GenDeathrow** [comment]
this should be fixed.. I am closing unless you find anything else
