### ISSUE TITLE
Rotten Food not compatible with Canola Seeds from RotaryCraft

### ISSUE THREAD

**Issue by Pyrolusite** [EnviroMine/EnviroMine-1.7#153]
Mod version : EnviroMine v.1.3.118 / RotaryCraft v.7a
Forge version : v.10.13.4.1481

When applying Rotten Food on Vanilla/Pam's HarvestCraft crops, a bonemeal effect is applied. However, it doesn't happen on RotaryCraft crops (Canola Seeds) and makes me eat it instead.

**Comment by Pyrolusite** [comment]
Now fixed on RotaryCraft's side. (v.7c)

**Comment by jHoyne** [comment]
Relevant to this Issue is there an API for adding values to rot

On 9 July 2015 at 18:27, Pyrolusite <notifications@github.com> wrote:

> Closed #153 <https://github.com/EnviroMine/EnviroMine-1.7/issues/153>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EnviroMine/EnviroMine-1.7/issues/153#event-352427188>.
>



-- 
Joseph Hoyne
Twitter <https://www.twitter.com/JosephHoyne>
Github <http://www.github.com/jHoyne>
