### ISSUE TITLE
Hypothermia bug

### ISSUE THREAD

**Issue by Nampa** [EnviroMine/EnviroMine-1.7#163]
Hi buddies, I have found a bug in enviromine 1.3.122.
When you have Hypothermia, the player starts to fly higher and higher.. I dont know why but im sure that this only happens when I start to have Hypothermia, so I have had to disable it in options.

By the way, congratulations for the mod, Its one of my favorites :)

**Comment by GenDeathrow** [comment]
https://github.com/Funwayguy/EnviroMine/issues/157
