### ISSUE TITLE
Remove global entity registration

### ISSUE THREAD

**Issue by Adaptivity** [EnviroMine/EnviroMine-1.7#167]
Please, don't use global entity ids [here](https://github.com/EnviroMine/EnviroMine-1.7/blob/028dafd8da453dc089bff2808da33281aff0aed5/src/main/java/enviromine/handlers/ObjectHandler.java#L208). Use mod entity registration instead. This will solve potential entity id conflicts. This will also fix this issue: https://github.com/Funwayguy/EnviroMine/issues/162
[Here the Forge issue](https://github.com/MinecraftForge/MinecraftForge/issues/1880) where LexManos states that modders shouldn't use global entity ids.
Galacticraft also recently removed global entity usage:
https://github.com/micdoodle8/Galacticraft/issues/1896

**Comment by SvEgiiVEteR** [comment]
1.7-3.0.12.376
problem still exists. or even the author did not correct mod?
or need to wait for your fix?

**Comment by Adaptivity** [comment]
The change will be available in the next version (377). I dunno why GC jenkins still not compiled it.

**Comment by SvEgiiVEteR** [comment]
thanks for the help) that explained the author)
