### ISSUE TITLE
I can't collect water

### ISSUE THREAD

**Issue by BasT94** [EnviroMine/EnviroMine-1.7#172]
So I'm excited about drinking water, make a bottle, but when I right-click in lake to pick up water, the game crashes. Why?

Here's the crash report:

http://pastebin.com/E1DRRgCL

**Comment by PitchBright** [comment]
Maybe this:

[14:01:35] [Server thread/WARN] [enviromine]: Failed to get ChangeLog file!
[14:01:35] [Server thread/WARN] [enviromine]: Failed to get WordPress News Page!
[14:01:35] [Server thread/WARN] [enviromine]: Failed to get/read versions file!
[14:01:35] [pool-2-thread-1/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@5ba8888[id=2d5ae54d-e772-32d1-b2d3-035fb9d14f66,name=Diógenes,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationUnavailableException: Cannot contact authentication server

Are you playing offline or something?

**Comment by GenDeathrow** [comment]
Make sure to list versions and mod list.  Where you in a custom buxom or anything?  Its saying there is no suchfield error "DEAD" and I have no idea why its doing that.. ill have to look at the code.. also make sure to use pastebin.com for long pieces of code.

**Comment by BasT94** [comment]
Yes, I play offline because my internet has limitations in terms of how much mbs I can spend in a month. Is that a problem?

— My minecraft: release 1.7.10-Forge 10.13.0.1158.
— Mods:
-AppleCore-mc1.7.10-1.1.0
-EnviroMine-1.3.122
-HungerInPeace-mc1.7.10-1.0.0
-InfernalMobs-1.7.10
-SpiceOfLife-mc1.7.10-1.2.4

Sorry, I don't know what a buxom is. And sorry, I already put the code in pastebin.

**Comment by PitchBright** [comment]
I'm no java whiz but it looks to me like the mod crashes because you're playing iffline. Try playing online for a minute.

**Comment by BasT94** [comment]
I tried it. And it worked! It seems I'm gonna have to use the internet every time I need water to drink... Well, whatever. Thanks!

**Comment by GenDeathrow** [comment]
Well that needs to be fixed anyways. Will  ?  Look into it still drinking water should have nothing to do with being online.. but I find it funny that no  .  Ones ever reported this before.

**Comment by BasT94** [comment]
It's not the drinking part, though. It's picking up the water to fill the bottle. I once removed the mod and I got the water just fine, and then I put the mod again and I drank what I had. But when I looked for water again, the game crashed.

Anyway, it's weird, but I'll leave that up to you. It's a great mod, so I'll play with what I can. Thanks :)
