### ISSUE TITLE
Shrinking with Hypothermia

### ISSUE THREAD

**Issue by sweetsosweet** [EnviroMine/EnviroMine-1.7#179]
Weird bug, but I developed hypothermia in cold water, and couldn't swim up because my character had shrunken to a very small size. In addition to that, since I was underwater I began running out of air, but once I did, I did not die. So I was alive, very small, and stuck underwater. I had to use /kill to get out. I'm using version: 1.3.124

**Comment by GenDeathrow** [comment]
I can already tell you this is not a bug.  Its a potion Id conflict. Go into configs and change the potion id's
