### ISSUE TITLE
when dehydration effect on me , it spawn random log under me

### ISSUE THREAD

**Issue by usa11131519** [EnviroMine/EnviroMine-1.7#196]
I'm using "EnviroMine-1.3.124"
Minecraft version 1.7.10
forge version "forge-1.7.10-10.13.4.1614-1.7.10"

**Comment by GenDeathrow** [comment]
This is because you need to go into enviromines configs and change the dehydration potion id to something else.. it has the same potion id as another mods potion effect..

**Comment by usa11131519** [comment]
ok i see , thanks a lot
