### ISSUE TITLE
Several problem with graveston caused by evniromine's physics

### ISSUE THREAD

**Issue by lightning02** [EnviroMine/EnviroMine-1.7#208]
I've discussed with one of the main OpenBlocks developers, and we ended up that what was causing the issue is in someway enviromine :l
You can find all the details here https://github.com/OpenMods/OpenBlocks/issues/787, I hope this could help to improve the code or at least raise a new compatibility with openblocks,
thanks for the attention :)

**Comment by PitchBright** [comment]
Here's where you can learn how to use Enviromine: https://github.com/EnviroMine/EnviroMine-1.7/wiki/
You'll want to look closely at the Physics section.

**Comment by lightning02** [comment]
is this syntax correct?
http://i.imgur.com/yUJkQIP.jpg
http://i.imgur.com/33LeWyt.png
because with this one seems not working still :l

**Comment by PitchBright** [comment]
S:10.Stability=none

in the config file found in /config/enviromine/profiles/default/Custom Properties/whateverthemodsnameis.cfg

```
##########################################################################################################
# blocks
#--------------------------------------------------------------------------------------------------------#
# Customise the physical properties and environmental effects of blocks
##########################################################################################################

blocks {

    tile_enviromine_gas_gas {
        S:01.Name=enviromine:gas
        I:02.MetaID=-1
        S:03.DropName=
        I:04.DropMetaID=-1
        I:05.DropNumber=-1
        B:"06.Enable Temperature"=false
        D:07.Temperature=0.0
        D:"08.Air Quality"=0.0
        D:09.Sanity=0.0
        S:10.Stability=none
        B:11.Slides=false
        B:"12.Slides When Wet"=false
    }
```

**Comment by lightning02** [comment]
I was able to add the correct config now, it works! :) Thanks alot Pitch

**Comment by PitchBright** [comment]
You're welcome :)  I'm glad it worked.

Please "close" this issue, now that we know it's not a bug, or incompatibility.

**Comment by lightning02** [comment]
Yes I will :)
one last question btw, why the tile entity name appears 2 times? 
for example in the screen you made: gas_gas

**Comment by PitchBright** [comment]
No idea. I didn't make that "gas_gas"... that's the default auto-generated naming of the section pertaining to the enviromine:gas block, in the config.

It also does it on some mojang blocks too, in the minecraft.cfg

```
blocks {

    tile_stone_stone {
        S:01.Name=minecraft:stone
        I:02.MetaID=-1
        S:03.DropName=minecraft:cobblestone
        I:04.DropMetaID=-1
        I:05.DropNumber=-1
        B:"06.Enable Temperature"=false
        D:07.Temperature=0.0
        D:"08.Air Quality"=0.0
        D:09.Sanity=0.0
        S:10.Stability=average
        B:11.Slides=false
        B:"12.Slides When Wet"=false
    }

    tile_grass_grass {
        S:01.Name=minecraft:grass
        I:02.MetaID=-1
        S:03.DropName=minecraft:dirt
        I:04.DropMetaID=-1
        I:05.DropNumber=-1
        B:"06.Enable Temperature"=false
        D:07.Temperature=0.0
        D:"08.Air Quality"=1.0
        D:09.Sanity=0.1
        S:10.Stability=loose
        B:11.Slides=false
        B:"12.Slides When Wet"=false
    }

```

You can label it anything you like, so long as it is unique. I could have edited my config file to label that section from 

```
tile_enviromine_gas_gas {
```

to

```
block_enviromine_gas {
```

or

```
tile_doesntmatter {
```

**Comment by lightning02** [comment]
yeah I took a look in vanilla cfg for those blocks, I was actually tryng to raise compatibility with Others mod torches like carpenter etc..
thanks again Pitch, I'm gonna close this, and I hope it could be useful for people that will come around here looking for infos and examples :)

**Comment by PitchBright** [comment]
No sweat. There's a couple of us in the IRC channel, if you need a hand with anything. IRC is better for help-type-stuff... than GIT... since GIT is supposed to be used for error-reporting and issue-tracking... not really for Tutorials/Help, etc. You're on IRC... ya gotta give us a chance to reply to your question though, sometimes it takes a day for us to notice it.
