### ISSUE TITLE
Frostbite/Hypothermia persist after death

### ISSUE THREAD

**Issue by axlegear** [EnviroMine/EnviroMine-1.7#212]
Once your legs freeze, it's game over forever, because dying and logging both do nothing to remove them.

**Comment by PitchBright** [comment]
There's an option to reset status effects after death, in the configs. It is notorious for not working as expected, but the running theory is that the true/false is inadvertently inverted in the code somewhere. Trying changing your config.

**Comment by axlegear** [comment]
It's set to 'false' but persists after death.  Switching it to 'true' did nothing, still frozen solid.  Am I just a statue now?  lol

**Comment by PitchBright** [comment]
You can close this issue, the problem has already been reported in a few other issues.

For reference:
#107 #148 #181

**Comment by axlegear** [comment]
oh wow, very very super old.  No update no fix?

**Comment by PitchBright** [comment]
No update, no confirmed fix. Some people have the problem, some people don't. Nobody's sure why just yet.

You can read the other issues, and maybe that will help you narrow it down a bit. KCauldron?

**Comment by axlegear** [comment]
No, only Forge, version 1566

**Comment by Bogdan-G** [comment]
in branch https://github.com/EnviroMine/EnviroMine-1.7/commits/Funwayguy have seen a fix(?)

**Comment by PitchBright** [comment]
Pardon?

**Comment by Bogdan-G** [comment]
@PitchBright in one of the branches of the repository would fix, but it was not included in the basis of the branch.

**Comment by PitchBright** [comment]
Which commit?

**Comment by Bogdan-G** [comment]
@PitchBright seems to be this: https://github.com/EnviroMine/EnviroMine-1.7/commit/06426ff0403a57e542399394c887266dc66647ae
