### ISSUE TITLE
Rotten meat and food perpetually rots

### ISSUE THREAD

**Issue by axlegear** [EnviroMine/EnviroMine-1.7#213]
Both will continue to rot even though they rot into the same items afterwards, making them unstackable and obnoxious.

**Comment by PitchBright** [comment]
I don't remember this being the case the last time I generated fresh configs. Eitherway, you can change it in the config yourself, the mod's settings are highly customizable.

**Comment by axlegear** [comment]
How?  I see no entry whatsoever affected rotten_flesh or rottenfood.

**Comment by PitchBright** [comment]
```
rottenFood {
    S:01.ID=enviromine:rottenFood
    I:02.Damage=-1

    # Set blank to rot into nothing
    S:"03.Rotten ID"=enviromine:rottenFood
    I:"04.Rotten Damage"=-1

    # Set this to -1 to disable rotting on this item    <---------------------------------------
    I:"05.Days To Rot"=-1
}
```

**Comment by axlegear** [comment]
cool, thanks!  I'll try to figure out how this works and where it goes and what to put for rotten_flesh.  I am not good at modding!  =D

Should probably fix them so they rot to nothing or don't rot by default

**Comment by PitchBright** [comment]
You're welcome. Please close this issue, so that the mod authors don't mistake this for a real bug report. Please use the forums or the #enviromine irc channel for help with stuff like this. The stuff you are reporting seems like stuff that's related to you not fully knowing how to configure the mod yet... Not actual "issues" (bugs) with mod. Github really isn't meant to be used as an online tech-support/tutorial type thing.

**Comment by axlegear** [comment]
It seems a bug to me because the configuration default does not make sense, and it is not normal to require a player to code to make a mod work normally.  So maybe minor but still seems a bug, just a bug with a workaround.

I am also unsure which forum is right?  There are many enviromine threads and all seem fairly inactive?

**Comment by axlegear** [comment]
What would I put to do the same for rotten flesh?

**Comment by axlegear** [comment]
The config issue mentioned in #211 also fixed this so rotten_flesh and rottenFood both do not rot by default

Seems the mod doesn't make the same defautl configs on server as client and that causes issues
