### ISSUE TITLE
I ask for permission

### ISSUE THREAD

**Issue by ENDERZOMBI102** [EnviroMine/EnviroMine-1.7#225]
Hi!
i loved this mod and decided to port it to newer versions of MC with the help of a friend, may i ask your permission to do so?

**Comment by PitchBright** [comment]
I believe you're good-to-go! Check it out:
https://github.com/EnviroMine/EnviroMine-1.7/issues/220#issuecomment-443963172

**Comment by ENDERZOMBI102** [comment]
ty didn't noticed when i read that issue
