### ISSUE TITLE
Feature Request: Provide alternate nausea effect

### ISSUE THREAD

**Issue by fuzzyray** [EnviroMine/EnviroMine-1.7#64]
The nausea effect in Minecraft actually makes me nauseous in real life.  It would be very nice if you could provide an alternate effect (toggled in the config) to be used with insanity as it would make the mod much more enjoyable for me to play.

**Comment by 710583** [comment]
If partial blindness isn't enough possibly blindness+night vision combo.

**Comment by Funwayguy** [comment]
Next update will include an option to switch nausea to blindness. Heatstroke will have night vision on top of that for a 'white out' effect
