### ISSUE TITLE
GUI defaults messed up

### ISSUE THREAD

**Issue by suprememiners** [EnviroMine/EnviroMine-1.7#67]
For some reason https://www.dropbox.com/s/suyqs2nxko7istk/2014-12-28_19.40.00.png?dl=0 keeps happing to everyone who logs in now.

You can fix by resetting the locations, but it sets it self back there if you reload the pack.

**Comment by suprememiners** [comment]
Any update on this? or is this still a problem or can't you recreate it.

if thats true on the client is the UI_Settings.dat file the file that stores all the Bar settings on the GUI. if so i will remove it and get the client to regenerate the file and see if that fixes the problem. if it does i believe the problem will lie with it just not saving and changes to the file. (Or my mod pack is special)

**Comment by Funwayguy** [comment]
@suprememiners Just be patient. @GenDeathrow is still on Holiday break and this code is more his expertise. We will look into this more when everyone is back into normal routines. This problem is something I have been able to recreate so it isn't just you.

**Comment by suprememiners** [comment]
ok, will do. Thanks :)

**Comment by GenDeathrow** [comment]
I had seen this before.  The way the GUI works is it save the old screen size in the save file. The only time I have seen this mess up is if you maximize the screen or full screen while it's loading up.  The old size in save file and new size don't sync up and it will keep the bars in the old position/smaller screen.  Maybe some one will have a better idea for a fix for this bit at the moment I couldn't come up with a better system. I will look into it more though. My holiday week is starting to slow down.

**Comment by Funwayguy** [comment]
@GenDeathrow it might be worth embedding a format version number into the config save files so you know which version of the formatting was used to create it and whether it needs resetting or not.

**Comment by Funwayguy** [comment]
Ok I implemented the above solution to the latest release which should fix this problem

**Comment by suprememiners** [comment]
Cool, Ill update as soon as i can :)
