### ISSUE TITLE
Version Page Crash

### ISSUE THREAD

**Issue by suprememiners** [EnviroMine/EnviroMine-1.7#68]
If you open up the enviromine menu and click on the news button, then the version page button it crashes you.

**Comment by Funwayguy** [comment]
I've fixed this for the next update

**Comment by suprememiners** [comment]
Thanks a lot.

**Comment by GenDeathrow** [comment]
Thanks for getting this @Funwayguy sorry that I have been out.

**Comment by Funwayguy** [comment]
@GenDeathrow no problem, I got your back ;D
