### ISSUE TITLE
Config backwards compatibility broken

### ISSUE THREAD

**Issue by thislooksfun** [EnviroMine/EnviroMine-1.7#69]
Originally reported here: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1293048-enviromine-a-little-bit-of-realism-1-7-10-new?comment=1961

**Comment by Scratchman** [comment]
Thanks for the quick update, unfortunately it didn't seem to fix the problem,

https://dl.dropboxusercontent.com/u/144602708/latest_0101.log

If you'd like me to provide more information, just let me know.

**Comment by Funwayguy** [comment]
Interesting... this is a new error I haven't seen before. What OS are you running?

**Comment by Scratchman** [comment]
This error happened on my home PC that i use to test out updates for the production server, so it is an exact copy of the production server. 

Windows 7 64 bit on a home PC running the last version of Java 7 64 bit.

Tomorrow i will be trying to run a new enviromine 74 and have it create new cfg's to see what happens, maybe it is something about the PC I'm running the test on.

**Comment by Scratchman** [comment]
I did a few runs today with the latest version, v75 of enviromine.

Log File, it seems to be having problems with buildcraft mostly, https://dl.dropboxusercontent.com/u/144602708/latest_0102.log

These are the configs it creates, when running enviromine v75, and allowing it to generate new files. https://dl.dropboxusercontent.com/u/144602708/enviromine_v75.rar

These are the configs v75 creates when there are already existing configs from v63. https://dl.dropboxusercontent.com/u/144602708/enviromine_v75_with_old_cfgs.rar

I've checked the folders i'm using for the test server and made sure they're not marked "read-only".

**Comment by Funwayguy** [comment]
I found the bug. Buildcraft has a '|' symbol in it's mod ID which is an illegal character in file names/directories

**Comment by thislooksfun** [comment]
Well that's a stupid bug. Makes sense though, I guess.

**Comment by Scratchman** [comment]
awesome :) thanks for the fix. So i guess buildcraft was the last problem then. All i have to do now is spend a bit of time integrating my cfg's with the new ones. Luckily, i have a couple of weeks now to do that. I'm looking forward to the new cave dim in our next update.

**Comment by Funwayguy** [comment]
Should be fixed in the latest update
