### ISSUE TITLE
Crash on generating new world

### ISSUE THREAD

**Issue by googlepox** [EnviroMine/EnviroMine-1.7#71]
Hey all, I get a crash on 1.7.10 with Enviromine 1.3.76 when generating a new world. 
Here is the report:
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 1/3/15 4:40 AM
Description: Exception in server tick loop

java.lang.ClassCastException: net.minecraft.world.gen.MapGenBase cannot be cast to enviromine.world.chunk.MapGenModifiedCaves
	at enviromine.world.chunk.ChunkProviderCaves.<init>(ChunkProviderCaves.java:72)
	at enviromine.world.WorldProviderCaves.func_76555_c(WorldProviderCaves.java:155)
	at net.minecraft.world.WorldServer.func_72970_h(WorldServer.java:654)
	at net.minecraft.world.World.<init>(World.java:245)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97)
	at net.minecraft.world.WorldServerMulti.<init>(WorldServerMulti.java:14)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:65)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 480168168 bytes (457 MB) / 1200746496 bytes (1145 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 58, tcache: 47, allocated: 1, tallocated: 55
	FML: MCP v9.05 FML v7.10.85.1231 Minecraft Forge 10.13.2.1231 105 mods loaded, 105 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	FML{7.10.85.1231} [Forge Mod Loader] (forge-1.7.10-10.13.2.1231.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Forge{10.13.2.1231} [Minecraft Forge] (forge-1.7.10-10.13.2.1231.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	ivtoolkit{1.0.2} [IvToolkit] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	PlayerAPI{1.1} [Player API] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	debug{1.0} [debug] (denseores-1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	battlegear2{1.0.6.3} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.6.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	CoFHCore{1.7.10R3.0.0B9} [CoFH Core] (CoFHCore-[1.7.10]3.0.0B9-57.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	BuildCraft|Core{6.2.6} [BuildCraft] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	BuildCraft|Energy{6.2.6} [BC Energy] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	IC2{2.2.658-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.658-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	GalacticraftCore{3.0.6} [Galacticraft Core] (GalacticraftCore-1.7-3.0.6.232.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	SpaceCore{4.0.8} [4Space Core] (4Space-1.7-p4.0.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	SpaceEuropa{4.0.8} [4Space Europa] (4Space-1.7-p4.0.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	SpaceHole{4.0.8} [4Space Worm Hole] (4Space-1.7-p4.0.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	SpaceIo{4.0.8} [4Space Io] (4Space-1.7-p4.0.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	SpaceMercury{4.0.8} [4Space Mercury] (4Space-1.7-p4.0.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	SpaceVenus{4.0.8} [4Space Venus] (4Space-1.7-p4.0.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Thaumcraft{4.2.2.1} [Thaumcraft] (Thaumcraft-1.7.10-4.2.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	abyssalcraft{1.8.0.1} [AbyssalCraft] (AbyssalCraft-1.7.10-1.8.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	ImmibisCore{59.0.5} [Immibis Core] (immibis-core-59.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	AdvancedRepulsionSystems{59.0.2} [Advanced Repulsion Systems] (adv-repulsion-systems-59.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	AdvancedMachines{59.0.2} [Advanced Machines] (advanced-machines-59.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (AdvancedSolarPanel-1.7.10-3.5.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	AncientWarfare{2.3.78-beta-MC1.7.10} [Ancient Warfare Core] (ancientwarfare-2.3.78-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	AncientWarfareAutomation{2.3.78-beta-MC1.7.10} [Ancient Warfare Automation] (ancientwarfare-2.3.78-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	AncientWarfareNEIPlugin{2.3.78-beta-MC1.7.10} [Ancient Warfare NEI Plugin] (ancientwarfare-2.3.78-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	AncientWarfareNpc{2.3.78-beta-MC1.7.10} [Ancient Warfare NPCs] (ancientwarfare-2.3.78-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	AncientWarfareStructure{2.3.78-beta-MC1.7.10} [Ancient Warfare Structures] (ancientwarfare-2.3.78-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	AncientWarfareVehicle{2.3.78-beta-MC1.7.10} [Ancient Warfare Vehicles] (ancientwarfare-2.3.78-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	animalsPlus{1.2} [Animals+] (animalsPlus-1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	antiqueatlas{4.0.1a-1.7.10} [Antique Atlas] (antiqueatlas-4.0.1a-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	AppleCore{1.0.1} [AppleCore] (AppleCore-mc1.7.10-1.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Aquaculture{1.2.3} [Aquaculture] (Aquaculture-1.7.10-1.2.5.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships] (ArchimedesShips-1.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	atum{0.6} [Atum] (Atum-1.7.10-0.6.34.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Automagy{0.17.1} [Automagy] (Automagy-1.7.10-0.17.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	baublelicious{1.0.4} [Baublelicious] (Baublelicious-1.7.10-1.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	betterstorage{0.11.3.123} [BetterStorage] (BetterStorage-1.7.10-0.11.3.123.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	BiblioCraft{1.9.1} [BiblioCraft] (BiblioCraft[v1.9.1][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Forestry{3.3.0.6} [Forestry for Minecraft] (forestry_1.7.10-3.3.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	BinnieCore{2.0-pre2} [Binnie Core] (binnie-mods-2.0-pre2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Botany{2.0-pre2} [Botany] (binnie-mods-2.0-pre2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	ExtraBees{2.0-pre2} [Extra Bees] (binnie-mods-2.0-pre2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	ExtraTrees{2.0-pre2} [Extra Trees] (binnie-mods-2.0-pre2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Genetics{2.0-pre2} [Genetics] (binnie-mods-2.0-pre2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Turbo{1.2.0} [�e�nMinecraft Turbo] (Turbo-1.7.10-1.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	BioMaterials{4.1.0} [�2�nBio Materials] (BioMaterials-1.7.10-4.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	AWWayofTime{v1.3.0a} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.0a-1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	WaslieCore{1.1} [WaslieCore] (WaslieCore-1.1_B43.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	BloodUtils{1.4} [BloodUtils] (BloodUtils-1.4_B0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	bountifulbreadsmod{1.0} [Bountiful Bread Mod] (bountifulbreadsmod-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	BuildCraft|Transport{6.2.6} [BC Transport] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	BuildCraft|Silicon{6.2.6} [BC Silicon] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	BuildCraft|Builders{6.2.6} [BC Builders] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	BuildCraft|Factory{6.2.6} [BC Factory] (buildcraft-6.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	eureka{2.2} [Eureka] (Eureka-1.7.10-2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	bcadditions{1.8.3} [Buildcraft Additions] (BuildcraftAdditions-1.7.10-1.8.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	ChickenChunks{1.3.4.16} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.16-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	CliffiesTaints{1.7.2-1.0} [Cliffie's Goos] (CliffiesGoos-1.7-alpha1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	BuildMod{v1.0} [Build Mod] (CoroUtil-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	CoroAI{v1.0} [CoroAI] (CoroUtil-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	ExtendedRenderer{v1.0} [Extended Renderer] (CoroUtil-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	ConfigMod{v1.0} [Extended Mod Config] (CoroUtil-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	CosmeticArmor{1.0.5} [Cosmetic Armor] (CosmeticArmor-1.7.10-1.0.5.B8-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	CraftHeraldry{1.1.3} [CraftHeraldry] (CraftHeraldry 1.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	VirusMod{1.2.0} [DiseaseCraft] (DiseaseCraft-Beta1.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	MoCreatures{6.3.0} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.3.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	DynamicLights{1.3.7} [Dynamic Lights] (DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	DynamicLights_onFire{1.0.4} [Dynamic Lights Burning Entity Module] (DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module] (DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	DynamicLights_dropItems{1.0.7} [Dynamic Lights EntityItem Module] (DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	DynamicLights_mobEquipment{1.0.7} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	DynamicLights_floodLights{1.0.1} [Dynamic Lights Flood Light] (DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	DynamicLights_otherPlayers{1.0.7} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	DynamicLights_thePlayer{1.1.3} [Dynamic Lights Player Light Module] (DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	dynamictanks{1.0} [Dynamic Liquid Tanks 2.1] (dynamictanks-1.1.04.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Enchiridion{1.1} [Enchiridion] (Enchiridion-1.7.X-1.2b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	EnderTech{1.7.10-0.3.0.358} [EnderTech] (EnderTech-1.7.10-0.3.0.358.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	enhancedbiomes{2.4.1 for MC 1.7.10} [Enhanced Biomes] (Enhanced Biomes 2.5 for MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	enhancedportals{3.0.9} [EnhancedPortals] (EnhancedPortals_1.7.10-universal-3.0.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	enviromine{1.3.76} [EnviroMine] (EnviroMine-v1.3.76.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	evilcraft{0.7.0b} [EvilCraft] (EvilCraft-1.7.10-0.7.0b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	TConstruct{1.7.10-1.8.1.build815} [Tinkers' Construct] (TConstruct-1.7.10-1.8.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	ExtraTiC{0.8.4} [ExtraTiC] (ExtraTiC-1.7.10-1.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	GalacticraftMars{3.0.6} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.6.232.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	radixcore{1.3.4} [RadixCore] (RadixCore-1.7.10-1.3.4-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	WarpTheory{1.7.10R1.0} [WarpTheory] (WarpTheory-1.7-1.0-24.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Xthuoth{1.1.1} [Xth'uoth: the Aberrant Realm] (Xth'uoth-1.7.10-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	YALSM{2.1.3} [Yet Another Leather Smelting Mod] (yalsm-2.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	lotr{Beta v21.3 for Minecraft 1.7.10} [The Lord of the Rings Mod] (z[1.7.10] The Lord of the Rings Mod B21.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	HungerOverhaul{1.7.10-beta.2.jenkins30} [Hunger Overhaul] (zzHungerOverhaul-1.7.10-beta.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	arsmagica2{1.4.0.005} [Ars Magica 2] (zzzAM2-1.4.0.006.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	denseores{1.0} [Dense Ores] (denseores-1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	JustAnotherSpawner{0.16.12} [Just Another Spawner] (JustAnotherSpawner-0.16.12.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by thislooksfun** [comment]
Whoops.

**Comment by Funwayguy** [comment]
Should be fixed next update
