### ISSUE TITLE
License/FAQ conflict

### ISSUE THREAD

**Issue by PigheadedGnu** [EnviroMine/EnviroMine-1.7#75]
Top notch mod. Thanks!

Your FAQ mentions that you prohibit code modification (in the context of mod packs specifically) but the CC BY NC SA (the SA part specifically) allows modification. You may want to adjust one or the other (or both). Cheers!

**Comment by thislooksfun** [comment]
Where is this FAQ?

**Comment by PigheadedGnu** [comment]
https://enviromine.wordpress.com/faq/

**Comment by thislooksfun** [comment]
Fixed! Thanks for pointing that out.
