### ISSUE TITLE
More localization support

### ISSUE THREAD

**Issue by Adaptivity** [EnviroMine/EnviroMine-1.7#76]
1) EM_Gui_Menu.java (lines 25-26, 49)
2) Gui_EventManager.java (line 54)
3) NewsPage.java (lines 25-26)
4) PostGuiList.java (lines 64, 72-91) (110, 119 not sure about these two)
5) EnviroKeybinds.java (lines 18-19)
6) http://i.imgur.com/BDfP54c.jpg
7) http://i.imgur.com/0VuRYFs.jpg
8) EnviroMine commands should be localizable too.

**Comment by GenDeathrow** [comment]
Alright will add these soon.  Thanks!

**Comment by Funwayguy** [comment]
Localisations have been added and should be in the next update of EnviroMine. Note that not all of your request could be added for various reasons. Notably the  '(Coming Soon)' text is going to be erased some time in future so there is no point in localising it and the EnviroMine commands are also not localised either, I don't think Minecraft's vanilla commands are localised anyway.

**Comment by Adaptivity** [comment]
@Funwayguy you will be surprised Minecraft's vanilla commands are localized :smile: Moreover many mods have localization support for commands.

**Comment by Funwayguy** [comment]
Well... this is awkward...next update maybe?

**Comment by Adaptivity** [comment]
Ok. Just reopen it to not forget about it.

**Comment by Adaptivity** [comment]
Also, a lot of addLine lines in PostGuiList.java not added to .lang file. But they should...

**Comment by GenDeathrow** [comment]
The AddLine method adds it into a scrollable list. The data f

**Comment by GenDeathrow** [comment]
For each line is grabbed from our website.  And can't be localized.

**Comment by 710583** [comment]
So no offline commands w/o a cache

**Comment by Funwayguy** [comment]
@710583 I assume you mean an 'offline news feed' and no that wouldn't really be useful anyway. It would be like putting away a newspaper so you could read another day when the information is possibly outdated and/or redundant.

**Comment by 710583** [comment]
Then how would you run commands offline if it has to find a server to get
the code from. I might not be understanding whats completely happening here.

**Comment by Funwayguy** [comment]
@710583 Um what? Are you talking about the commands that you type in game or the news feed in the menus? Either way I think you've completely misunderstood the conversation topic.

Also, not to be rude or anything but I'm not sure it's necessary to involve yourself with the issue at hand unless you have additional details that could help resolve it otherwise the conversations and questioning between people gets confusing and ends up notifying people who don't need to be such as @Adaptivity. If you have an important question about something that isn't relevant to all persons involved in the current thread or the issue, please open up a separate issue thread.

**Comment by Adaptivity** [comment]
Why "addLine" strings can't be translated? For example line 74 in PostGuiList.java can be translated. It seems to be same as the others "addLine" strings.

**Comment by Funwayguy** [comment]
@Adaptivity Oh I see where you mean now. At first I thought you mean the AddLine functions used in the News Feed. Yea those ones shouldn't be too hard to sort out, thanks for pointing that out

**Comment by GenDeathrow** [comment]
@Adaptivity well next update should support more localizations as well as commands.  Sorry I didn't understand what you meant the first time about the addlines.  But me and @Funwayguy got it all sorted out.  Thanks for pointing those things out. Some times we over look things that don't outright break our mod.

**Comment by Adaptivity** [comment]
Also, what about lines 69, 130, 139 in PostGuiList.java? I guess they can be localized too.

**Comment by GenDeathrow** [comment]
I don't think there is a real reason for it.. the "posted by" comments will be translated but everything else will be English. and line 69 is only really shown on Dev versions.

**Comment by Adaptivity** [comment]
Well, at least "posted by" will be translated. I want to translate as much as possible :smile:

**Comment by Funwayguy** [comment]
This appears to have been fully resolved so I'm closing the issue
