### ISSUE TITLE
Dimension Physics Config/Whitelist?

### ISSUE THREAD

**Issue by reihned** [EnviroMine/EnviroMine-1.7#77]
Would it be possible to toggle stability, or potentially have custom stability, in entire dimensions?

i.e. Galacticraft Space Station, with micro-gravity it doesn't make sense if the stability of say aluminum blocks has the same stability as in the Overworld.

I've looked over the configs and documentation and cannot seem to find such an option. 

Currently I am resorting to configuring all Galacticraft blocks, and only using them to build space stations stations, but it would be awesome to have separate stability per dimension.

Love the mod, btw.

**Comment by thislooksfun** [comment]
First off: not a terrible suggestion. I get where you're coming from. However, the number of configs we have already is massive and complex. I'm not saying its a no, that's up to Funwayguy or GenDeathrow, as they know the configs better than I do. But just keep in mind that it would almost certainly result in a lot more config files.

**Comment by kane-thornwyrd** [comment]
To be exact, mathematically speaking, it's adding a new dimension to the matrix the confs are… Maybe being able to change the "gravity" used in physic calculation per world would be an easier answer ?

**Comment by Funwayguy** [comment]
Stability per dimension would not be easily done but turning off physics for a particular dimension/chunk is possible and I already plan on adding that in soon.

@kane-thornwyrd Gravity isn't a factor in the calculations mainly because they tend to be a bit too processing intensive for Minecraft.

**Comment by reihned** [comment]
Looking forward to turning off physics for particular dimensions/chunks, especially chunks. The chunk isolation would provide for some interesting contained floating castles in multiplayer server setups. Totally imagining a minecraft 'Tribes' game now.

Also an idea on potentially doing different stability per dimension, with consideration to the configs:
Would it be possible to allow config to set a multiplier on the stability per dimension?

**Comment by Funwayguy** [comment]
@reihned Dimension influencing stability types gets messy. You'd be basically be adding every base stability type to every dimension config to just to apply modifiers to the various options. I just don't think it's very reasonable.

Here's a screen shot of the new "No Physics" block in action:
http://puu.sh/eMuM5/1624158119.png
(Chunk on the right has physics disabled while the left does not)

**Comment by kane-thornwyrd** [comment]
I'm taking a try at implementing block gravity/friction/stability in MC… I won't dare to even think I could do better or even reach your level, it's just my way to start mod making… If it happend that I achieve releasing something, which I highly doubt of, I'd like to make it somehow an Enviromine Addon or something along those lines.

**Comment by Funwayguy** [comment]
Keep me posted on how that goes and if you need any help or suggestions on handling said physics then let me know.
