### ISSUE TITLE
Unique entity IDs

### ISSUE THREAD

**Issue by Adaptivity** [EnviroMine/EnviroMine-1.7#80]
I'm almost 100% sure it is not necessary to give single ID for entity. As I know it possible to give entity unique ID and this will prevent any entity ID conflicts like this: https://github.com/CrazyPants/EnderIO/issues/1749 I know there are a config option for it. But why you need config option if you can make entity IDs unique? Simple example how entity IDs were removed from Galacticraft: https://github.com/micdoodle8/Galacticraft/commit/c31400a465911e01f7c18351baf95909668e66bc

**Comment by thislooksfun** [comment]
Ah. So that's how you do it. XD

**Comment by Funwayguy** [comment]
It has been changed for the next update.

**Comment by Adaptivity** [comment]
Thanks.
