### ISSUE TITLE
Unauthorized running a mod ?

### ISSUE THREAD

**Issue by niccosaint** [EnviroMine/EnviroMine-1.7#82]
When trying run minecraft with EM crashes me with error
 java.lang.SecurityException: UNAUTHORIZED USE OF MOD ENVIROMINE
for full error [CLICK HERE](http://pastebin.com/aXcv9ADp)

**Comment by Funwayguy** [comment]
Where did you obtain your copy of the mod from?

**Comment by niccosaint** [comment]
here

**Comment by Funwayguy** [comment]
I just checked the timestamp in the log and it looks like you were unfortunate enough to have installed the mod just as update 1.3.93 was released rendering the old key as expired. I suggest updating to 1.3.93 however we can manually issue you an authentication file if necessary.

**Comment by niccosaint** [comment]
so that means that i have download again mod ?

**Comment by Funwayguy** [comment]
That would be the easier solution yes. The issue was just unfortunate timing that's all. Version 1.3.92 didn't work server-side anyway.

**Comment by niccosaint** [comment]
ok, problem fixed

**Comment by GenDeathrow** [comment]
The new authorization is to help deter and inform ppl of ppl stealing mods for the purpose of hiding them behind adfly links to make money or adding viruses to it.

**Comment by GenDeathrow** [comment]
(My phone posted too early) but this function will prolly change a few times as this is a brand new feature. And thier are bugs that will need to get fix/found.
