### ISSUE TITLE
Gregtech food will not Rot?

### ISSUE THREAD

**Issue by dahjin** [EnviroMine/EnviroMine-1.7#83]
as the title says any food added from GT seems to not spoil at all is there a way to fix?
(https://cloud.githubusercontent.com/assets/8744819/5917810/6a1e2478-a5ef-11e4-9e33-0a3d0a4f4e91.png)

**Comment by Funwayguy** [comment]
Have you tried adding custom spoiling configs for them?

**Comment by Funwayguy** [comment]
No response and this is usually possible with custom configs, closing...
