### ISSUE TITLE
[Bug] Stats Freezing

### ISSUE THREAD

**Issue by artdude543** [EnviroMine/EnviroMine-1.7#84]
Using version 1.3.94 and as you know we enabled the keep stats on death feature and it seems the heat/water levels are also freezing. Seems to happen on relog after you have died. I can send logs if you want them, or join ts when ya about and we can explain easier then. @Funwayguy

**Comment by Funwayguy** [comment]
Oops. I'll fix that up soon

**Comment by artdude543** [comment]
Yay for timezones :P Umm, I'll be around a tad longer tonight so should be around when you're up and around.

**Comment by DrStage** [comment]
Hi!
I've encountered the same problem with version 1.3.96 on my server (not sure about singleplayer).
It starts fine, but after a while the server log shows this:

22:24:34 CONSOLE: WARN]: More than one exception was raised. Will report only the first one and log others.
22:24:35 CONSOLE: Source) [?:1.7.0_67]
22:24:35 CONSOLE: ERROR]: FMLIndexedMessageCodec exception caught
22:24:35 CONSOLE: Source) [?:1.7.0_67]
22:24:35 CONSOLE: ERROR]: SimpleChannelHandlerWrapper exception
22:24:35 CONSOLE: Source) [?:1.7.0_67]

and Enviromine stops working.

**Comment by artdude543** [comment]
I think for now @Funwayguy I'll disable the feature, it also needs tweaking / changing on how the saving works with effects. We ended up with a loop with constant dying from heat stroke. (Which is not bad but kinda annoying when your trying to cool off)

**Comment by Funwayguy** [comment]
@DrStage That's a very interesting error. Didn't think the network side of trackers would crash but apparently so. At least now I have somewhere to start looking for bugs and problems.

**Comment by GenDeathrow** [comment]
@DrStage Funwayguy made some changes to this network and trackers.  May see if build 101 works for you guys.

**Comment by GenDeathrow** [comment]
@artdude543 see above post.

**Comment by artdude543** [comment]
Yeah I've been using the newest builds still testing it though. Me and @Funwayguy hang on ts testing things to fix it while lecturing me on modding xD

**Comment by GenDeathrow** [comment]
Well does everything seem to be working?

**Comment by GenDeathrow** [comment]
Well does everything seem to be working?

**Comment by DrStage** [comment]
Seems to work now, had no issue with the stats tracker in v.101
