### ISSUE TITLE
Player jitters in DIM 0

### ISSUE THREAD

**Issue by erima** [EnviroMine/EnviroMine-1.7#87]
After updating to 1.3.99 the player suddenly jitters uncontrollably. I'm not exactly sure what triggered it. I was spending most of the time in a Mystcraft world, and there were some gravel/dirt cave-ins that hit me. Leaving the world for DIM 0 I started shaking like I was falling through a block but then going back up. Going into other dimensions seems to stop it, but it starts again upon return. Removing Enviromine entirely stops the behavior. 

I'd check against the previous version but it's now telling me that I'm not using a registered mod and crashes.

**Comment by Funwayguy** [comment]
Hmm... although I'm not 100% sure what's causing it either although I assume the dynamic Mystcraft dimensions are influencing it somehow. As for the authentication crash, that's a something we're working on. Currently legacy build do not work with the authentication yet.

**Comment by iseejoe** [comment]
Like to add that I too am suffering the same problem and do not have mystcraft installed

**Comment by GenDeathrow** [comment]
@Funwayguy could this be because of earthquake.  I don't think the sound effects are working.

**Comment by erima** [comment]
Are there any other signs to look for besides sound and jitter? I could try to verify that.

**Comment by egeis** [comment]
The area around the location of an earthquake I found constant jittering.  The signs are pretty obvious in a superflat world, a rift (small version of a surface ravine, appears filled with lava somewhere around 10 to 15 blocks high, additionally the earthquake destroyed the bedrock (Unintended or not?).

**Comment by erima** [comment]
I have a very deep hole that has lava at the bottom and I swear it wasn't there before. I'm guessing thats the culprit. I definitely have sound on and heard nothing. 

I guess I would have expected more physics - blocks moved, loose dirt falling, etc.

**Comment by GenDeathrow** [comment]
Yup that's an earthquake. You prolly missed the actual dirt falling.  Earthquakes are very destructive.
