### ISSUE TITLE
EnviroMine dont't work in SMP

### ISSUE THREAD

**Issue by BlackwingDave** [EnviroMine/EnviroMine-1.7#89]
Hey since I have updated to the latest version 13.99 does not seem to work correctly the mod . The s seen as the beginning everything is normal. But at some point all ads seem to stand still , after a repeated login , all values ​​such as temperature odere thirst to 37 degrees and 100 % and no longer fall

**Comment by GenDeathrow** [comment]
I'll take a look at this, but I think @Funwayguy did some editing to this. And not sure what's changed yet

**Comment by BlackwingDave** [comment]
I still have to add the effect occurs if you make a relogg and disappears after a reboot of the server .

**Comment by GenDeathrow** [comment]
@Funwayguy is going to try and take a look at this issue. He doesn't have as much time as he use too. He says he has a general idea whats going on though

**Comment by BlackwingDave** [comment]
Okay Thanks ^^

**Comment by GenDeathrow** [comment]
I think we may have got this working in the new build 101. Check it out to see if syncing is working again

**Comment by BlackwingDave** [comment]
okay it works
