### ISSUE TITLE
Temperature problems

### ISSUE THREAD

**Issue by Deathdemon95** [EnviroMine/EnviroMine-1.7#90]
It's a little hard to explain, but basically, while the temperature around me (represented by the two white lines in the meter) will change as normal, my actual temp (as represented by the solid white dot) will always stay within the warmer side of green. No matter what.
I've been submerged in frozen water, no armor, and drinking bottles of ice water in a snowy biome at night, and there is literally no change.
Please help.

**Comment by GenDeathrow** [comment]
go into enviromines ingame menu and turn on status text tell me if you see a change? Also is this ssp or smp?

**Comment by Deathdemon95** [comment]
This is SSP, and apparently, there seems to be a change. However, it seems to be an incredibly slow one. I'm not sure if that's normal, but if it is, is there a way to change that? Because I'd prefer temperature to effect my body a bit more rapidly

**Comment by GenDeathrow** [comment]
yeah.. there is a way to change its in your config file. We also have an ingame editor you can use.. or a good ol' text editor will work as well. There are multipliers to make it harder.

https://github.com/Funwayguy/EnviroMine/wiki/General-Configuration

https://github.com/Funwayguy/EnviroMine/wiki/Custom-Configs

**Comment by Deathdemon95** [comment]
Well hey, that's useful
Thanks! Sorry to be annoying like this!
I appreciate the speedy help!

**Comment by GenDeathrow** [comment]
No problem.. be on the look out. We are going to be rewriting the status effect code to be much different. and temp will display diff as well. as complex as the code has gotten.. its in need to improvement.
