### ISSUE TITLE
No freezer sound (Solved)(read for temp fix)

### ISSUE THREAD

**Issue by tatjam** [EnviroMine/EnviroMine-1.7#91]
Hi there:

Although now esky has a nice sound, i cannot hear anything when opening or closing the freezer. Is it only me? Hope it helps.
Cheers

**Comment by GenDeathrow** [comment]
I am not at home right now, but I'll check it later.  It was working when I had pushed to git hub.

**Comment by GenDeathrow** [comment]
Actually I think it may be a naming issue.  If you can open the jar up with a zip program, go to the sounds under resources an locate the freezer sounds and make sure it's lowercase. I'm not sure if it's case sensitive. It may be something that works in my dev environment but not when built. 

If it's not make it lowercase and see if that fixes it.  This of course is a temp fix until the next update.

**Comment by tatjam** [comment]
Thanks Gen, that did the trick. Nice sound now.
Cheers!

**Comment by GenDeathrow** [comment]
I'll get this fixed on the next update we do. Should have caught that, but now I know for next time.  We learn by making  mistakes. 

I am leaving this open so everyone can see how to fix it temporally. This is for build 101.

**Comment by GenDeathrow** [comment]
Should be fixed in latest build 11.3.104
