### ISSUE TITLE
(Mac) .DS_Store file causes crash

### ISSUE THREAD

**Issue by GenDeathrow** [EnviroMine/EnviroMine-1.7#92]
> Plus_Minus said:
> I'm having some trouble with the mod messing with a .DS_Store file. In /CustomProperties the mod     > sees the .DS_Store.cfg as another custom config. Eventually /CustomProperties is filled with >.DS_Store(a bunch of numbers).error files and whenever I go into "Custom configs" in the Enviromine >!menu, Minecraft crashes. I have to constantly delete all those files via the terminal. Is it possible to >!make the mod ignore hidden files on mac?

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1293048-enviromine-a-little-bit-of-realism-new-physics?comment=2171

**Comment by Funwayguy** [comment]
I believe @thislooksfun1 uses a Mac and can bug test this. I don't have the OS available to be to test this and my Ubuntu PC isn't really in a state of usability at the moment.

**Comment by fuzzyray** [comment]
I use a Mac as well and can also test.

**Comment by GenDeathrow** [comment]
Well for the most part I think I can just put in an ignore if statement. And prolly double check each file is correct format before loading.

**Comment by GenDeathrow** [comment]
Ok I added in some checks for this file specifically and also to avoid hidden files.

**Comment by GenDeathrow** [comment]
This should be resolved in build 104.. I will leave this Open for a little, while until you confirm this issue is gone.

**Comment by GenDeathrow** [comment]
I'm going to close and assume it is working
