### ISSUE TITLE
Custom decay is not taken

### ISSUE THREAD

**Issue by BlackwingDave** [EnviroMine/EnviroMine-1.7#94]
Hi I have just noticed that a custom setting for rotting food will not be accepted for items Vanilla , but modded items.

Tested with v. 101

**Comment by GenDeathrow** [comment]
You man that setting up custom configs for vanilla items don't seem to work? and modded items do? Will take a look at this.

**Comment by Funwayguy** [comment]
Have you checked that the default entries in minecraft.cfg are removed in order to load your custom entries (or you could instead edit the defaults)? This a common mistake that a lot of people tend to make

**Comment by BlackwingDave** [comment]
the problem no longer exists

**Comment by GenDeathrow** [comment]
I this brings up the fact that I think I will add in a message when a file gets overriden.

**Comment by GenDeathrow** [comment]
Build 104 will now tell you if your config item gets overwritten from another config file.
